import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Navigation from "@/src/lib/components/Navigation";
import Particles from "@/src/lib/components/Particles";
import Glow from "@/src/lib/components/Glow";
import Footer from "@/src/lib/components/Footer";
import { UserProvider } from "@/context/UserContext";
import "./globals.css";



const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
  hideNav?: boolean;
}>) {

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="min-h-screen bg-linear-to-br from-gray-900 via-orange-900/20 to-gray-900 text-white overflow-hidden relative flex flex-col">
          <UserProvider>

            <Navigation />

            <main className="flex-1 overflow-hidden">
              <Particles />
              <Glow />
              {children}
            </main>

            <Footer />

          </UserProvider>
        </div>

      </body>
    </html>
  );
}
